### ISSUE TITLE
PI4 dual display with common context

### ISSUE THREAD

**Issue by ArtArt0** [matusnovak/rpi-opengl-without-x#8]
Hi!

I ran an issue:
when I use the code with LCD and HDMI display together, I can not activate the second display (and surface) errorless.

First I use context 1:
eglMakeCurrent(ctx->eglDisplay, ctx->eglSurface, ctx->eglSurface, ctx->eglContext)

Than the context 2 with the same eglContext:
eglMakeCurrent(ctx2->eglDisplay, ctx2->eglSurface, ctx2->eglSurface, ctx->eglContext)

And the second gives EGL_BAD_CONTEXT.

Anyway if I use in the second one with ctx2->eglContext at the 4th parameter, it succeeded, but it gives a blank screen (because the ctx2 contains nothing)

What is the problem? Can U give me an example for using 2 displays with the same eglContext?

**Comment by matusnovak** [comment]
Hi @ArtArt0 

Are you using Raspberry Pi 4? How is the LCD connected to the board?

**Comment by ArtArt0** [comment]
With the standard cable (for the official 7'' LCD). Why? It shows the console successfully.

**Comment by matusnovak** [comment]
Are you able to get any OpenGL output if you use only the LCD display without second HDMI screen? (I am trying to figure out if this is DRM device problem or EGL problem).

**Comment by ArtArt0** [comment]
Yes, I have no problem with it.

**Comment by matusnovak** [comment]
I am not 100% sure because I haven't tried two displays, but I think you may need to call `eglInitialize` twice, once for the LCD display and second time for the HDMI display. As seen here: https://github.com/matusnovak/rpi-opengl-without-x/blob/master/triangle_rpi4.c#L48 with the correct EGLDisplay. 

The `drmModeGetResources` and `drmModeGetResources` is used to get the EGLDisplay as shown here: https://github.com/matusnovak/rpi-opengl-without-x/blob/master/triangle_rpi4.c#L48 so I believe you should have two resources for your two displays.

Could you try iterating over the `drmModeRes *resources` as shown here: https://github.com/matusnovak/rpi-opengl-without-x/blob/master/triangle_rpi4.c#L28 and check if you have multiple connectors? It may be that you have two connectors that are `DRM_MODE_CONNECTED`. When you get the connector C structure then you can iterate over the `connector->modes` to get the resolution to identify the display.

**Comment by ArtArt0** [comment]
Finally I think I figured out!

The problem was in the getDisplay(): the `gbm_create_device` must call only once, and the second display uses the first `gbmDevice` struct.

Anyway the cardX device must open once too.

**Comment by matusnovak** [comment]
Awesome! You would be willing to share the code? I would like to give it a try and maybe make a sample code out of it and put it here in this repository.

And yeah, the device `/dev/dri/card1` is the GPU so selecting card0 would not work. I originally thought the cardX is the HDMI<->GPU port (or something like that) but I was wrong.

**Comment by ArtArt0** [comment]
Sorry, I can not share it, but I hope it easy to implement to anyone now.

Anyway not always the card1 is the right one. You should detect with the following mode:
```
open card0
if not OK or getdisplay is not OK:
  open card1
  if OK:
    getdisplay
```

**Comment by matusnovak** [comment]
That's alright. I will play around with that when I get the chance and will create a sample code as well. 

Closing for now.
